### ISSUE TITLE
Matching cascade vs Vanilla matching

### ISSUE THREAD

**Issue by Yibin122** [dyhBUPT/StrongSORT#1]
Thanks for your excellent work!
Regarding ablation study, I wonder if matching cascade is really redundant in the case of less powerful tracker. Have you compared baseline with baseline+woC (no other tricks present) in your experiments?

**Comment by dyhBUPT** [comment]
Thanks for your interest in our work!
I've just conduct an ablation experiment as you asked.
As we can see, matching cascade works well for poor tracker, but worsens performance for stronger tracker.
Please feel free to contact me if you have any questions
![image](https://user-images.githubusercontent.com/99722489/156351739-9f152883-5ed0-4302-839e-12ff4bace0d2.png)
