### ISSUE TITLE
Run Strong sort using my own weights

### ISSUE THREAD

**Issue by javidefuentes** [dyhBUPT/StrongSORT#101]
Hi, I have trouble with running strong_sort,py.
I trained on my own a ReID network and got my own weights .pth.
Now, I want to use those weights to do vehicle tracking using a specific video I have.

Since I believe this code needs the detections from the video, I used yolov8 and generated a directory which contains a folder for each frame, and in each frame a txt containing all of the detections

<img width="266" alt="image" src="https://github.com/dyhBUPT/StrongSORT/assets/90854896/741e444d-c55e-473f-b431-dfc03426e173">

My question is if I have to do anything else to be able to run strong_sort.py in order to do tracking on my video.

Thanks

**Comment by dyhBUPT** [comment]
Hi, our codes follow the pipeline of the source codes of DeepSORT. Therefore, you need to **prepare one `.npy` file for every video**.

This file has the size of `N x (10+C)`, which contains `N` bboxes of the video, and `10` for detection information (from YOLOv8 in your case), `C` for appearance features (from your own ReID network).

The `10` dimension means `frame_id, -1, x, y, w, h, score, -1, -1, -1`. Here is an example:
```
1,-1,834.30,490.39,70.20,88.42,0.76,-1,-1,-1
1,-1,901.80,491.40,54.00,96.53,0.86,-1,-1,-1
2,-1,1091.47,501.19,78.30,108.68,0.42,-1,-1,-1
2,-1,147.83,482.63,52.65,124.87,0.11,-1,-1,-1
```

I believe this will help you~
Best wishes.

**Comment by Thomas-CHOCHOY** [comment]
Hi, please, can you tell me how you trained your reid model?

**Comment by dyhBUPT** [comment]
> Hi, please, can you tell me how you trained your reid model?

Please refer to some open-source ReID repos, for example, FastReID.
