### ISSUE TITLE
'NoneType' object has no attribute 'groups'

### ISSUE THREAD

**Issue by TimTreurniet** [dyhBUPT/StrongSORT#102]
Hi,

Not sure if this is a google error maybe, but I was experimenting with adding Strongsort to a git repoand including it in unit tests. It fails 4/5 times (so not always) when downloading weigths.
`gdown.download(model_url, str(strong_sort_weights), quiet=False)`
I'm providing: url = 'https://drive.google.com/uc?id=1z1UghYvOTtjx7kEoRfmqSMu-z62J6MAj', output = 'osnet_x0_25_market1501.pt'

```
        if gdrive_file_id and is_gdrive_download_link:
            content_disposition = six.moves.urllib_parse.unquote(
                res.headers["Content-Disposition"]
            )
            m = re.search(r"filename\*=UTF-8''(.*)", content_disposition)
            print(m)
>           filename_from_url = m.groups()[0]
E           AttributeError: 'NoneType' object has no attribute 'groups'

.venv/lib/python3.10/site-packages/gdown/download.py:260: AttributeError
```

**Comment by TimTreurniet** [comment]
yeah looks like an issue with [gdown](https://github.com/wkentaro/gdown/issues/291)

**Comment by dyhBUPT** [comment]
Hi, it seems not a relevant issue for this repo. We don't provide any ckpt for OSNet.

**Comment by TimTreurniet** [comment]
Yeah I'll close this. If anyone is having the same issue: pip install gdown==v4.6.3
