### ISSUE TITLE
Increasing max_age parameter does not affect number of new tracking IDs assigned

### ISSUE THREAD

**Issue by lindsayveazey** [dyhBUPT/StrongSORT#104]
First, thank you very much for your contribution- a StrongSORT fork has worked very well for my detection and tracking project!

I am tracking wildlife in videos. Sometimes, a bird is static across thousands of frames; I observe a bounding box when the bird is detected, and this box blinks on and off, which is not surprising. I have code to backfill the false negative frames.

I notice that even between very, very short non-detections (< 10 seconds), a static bird will be assigned a new tracking ID. My initial solution was to increase `max_age` a _lot_ to give the model more leeway to "remember" that bird X is at position Y. However, no matter how high I push `max_age`, the model does not change its number of newly assigned tracking IDs.

Is there any solution to this problem? Thank you.

**Comment by dyhBUPT** [comment]
Hi, glad to hear that StrongSORT works well in your project~

In your case, it may be caused by two reasons:
- the tentative mechanism in DeepSORT.
- high motion or appearance cost.

Please debug to find out the reasons.
