### ISSUE TITLE
Display the result

### ISSUE THREAD

**Issue by TanganHitam1** [dyhBUPT/StrongSORT#106]
I want to know how to display the result as video

**Comment by dyhBUPT** [comment]
Hi, we didn't modify the visualization codes of [DeepSORT](https://github.com/nwojke/deep_sort).
Therefore, you can try to visualize the results by setting `display=True` here:
https://github.com/dyhBUPT/StrongSORT/blob/fe70b4276e176d04b049c923eb3e3231c2ae7c6b/strong_sort.py#L24-L34

**Comment by TanganHitam1** [comment]
even if it's using AFLink and GSI? because what I see is the "run" code is before the AFLink and GSI code

**Comment by dyhBUPT** [comment]
Oh, you are right, So it is recommended to write new visualization scripts.
