### ISSUE TITLE
Detections with own dataset

### ISSUE THREAD

**Issue by caarmeecoorbii** [dyhBUPT/StrongSORT#107]
Hello, thank you for your repository as it has been very helpful for my final degree project. I tried your method with my own dataset and it really improves the results a lot. Now, I want to further improve my results. Using the 'generate_detections.py' file, I am able to generate detection features based on FastReID. This gives me a .npy file for each sequence. I would like to edit this .npy file to add more detections separately. Could you tell me the structure followed by these .npy files so that I can add additional detections?"

Thanks!

Carme

**Comment by dyhBUPT** [comment]
Hi, glad to hear that StrongSORT works in your case.
For your question, please refer to this issue https://github.com/dyhBUPT/StrongSORT/issues/28.

**Comment by caarmeecoorbii** [comment]
Hi, thank you for providing this information. I have a question regarding the 2048 features mentioned in issue #28. Are these features the result of applying FastReID? I'm asking because I've generated detections using other methods to potentially improve results in StrongSORT.

Now, I want to add these detections to the .npy file, but I'm unsure about obtaining features for these detections. How would I go about passing them to FastReID for feature extraction?

In the generate_detections.py file, I know it generates these features from the input detection .txt files. So, would it be possible for me to edit this script to accommodate the new detections?

Carme Corbi

**Comment by dyhBUPT** [comment]
Yes, these features are from FastReID. So please modify the `generate_detections.py` for your requirements.

**Comment by dyhBUPT** [comment]
If you have "off-the-shelf tracking results" (e.g., multiple txt files), and want to improve the performance upon it, it is recommended to try some "offline post-processing" methods, e.g., global link, split-and-connect, interpolation, etc.

BTW, why not directly inputting the raw detections and features into StrongSORT? SORT is an outdated method.

**Comment by caarmeecoorbii** [comment]
Thank you for your reply. Do you know any post processing methods that get good results for MOT? Sorry for the confusion, I meant StrongSORT.

**Comment by dyhBUPT** [comment]
For post-processing, this repo supports interpolation and appearance-free global link.
Indeed, you can try appearance-based link, which is expected to achieve better results.
Based on StrongSORT, you can also try to borrow other plug-and-play tricks from other SOTA works, e.g., BYTE.

**Comment by caarmeecoorbii** [comment]
Thank you so much! Yes, I tried AFLink and it improves my results. But still object association could be improved as many new ids are assigned for players. Also, in the dataset that I am using, which are of soccer players, the detections when they are in a lot of movement are not accurate.

**Comment by dyhBUPT** [comment]
Maybe you can try to release the motion constraints.

**Comment by caarmeecoorbii** [comment]
Apologies, but which part of the code are you referring to?

**Comment by dyhBUPT** [comment]
All parts related to motion cost and matching can be considered.

**Comment by caarmeecoorbii** [comment]
do you think if I modify the hyperparameters I could get better results?

**Comment by dyhBUPT** [comment]
yes, it usually works.

--------------原始邮件--------------
发件人："caarmeecoorbii ***@***.***&gt;;
发送时间：2024年3月30日(星期六) 下午3:06
收件人："dyhBUPT/StrongSORT" ***@***.***&gt;;
抄送："dyhBUPT ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [dyhBUPT/StrongSORT] Detections with own dataset (Issue #107)
-----------------------------------

 

 
do you think if I modify the hyperparameters I could get better results?

**Comment by caarmeecoorbii** [comment]
I tried changing the value of EMA_alpha to 0.8 with this command : 
python strong_sort.py MOT16 test --BoT --EMA --EMA_alpha 0.8 --NSA --MC --woC --AFLink   but I get the following error: 
![image](https://github.com/dyhBUPT/StrongSORT/assets/92037229/8df95967-cbc4-4ee2-b87e-00eccd3309eb)

**Comment by dyhBUPT** [comment]
Oh, to use `--EMA_alpha` in the command line, you should specify the type of `--EMA_alpha` to `float` in `opt.py`.

**Comment by caarmeecoorbii** [comment]
Apologies for the digression, but I was wondering if you happen to know whether DeepSORT tracker can be trained? I've modified the parameters of StrongSORT and managed to achieve slightly better results, but the ID assignment still isn't quite accurate. Therefore, I'd like to train the DeepSORT tracker if possible, as StrongSORT cannot be trained.

**Comment by dyhBUPT** [comment]
In DeepSORT, only the detector and ReID model can be trained.

--------------原始邮件--------------
发件人："caarmeecoorbii ***@***.***&gt;;
发送时间：2024年4月5日(星期五) 凌晨1:45
收件人："dyhBUPT/StrongSORT" ***@***.***&gt;;
抄送："dyhBUPT ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [dyhBUPT/StrongSORT] Detections with own dataset (Issue #107)
-----------------------------------

 

 
Apologies for the digression, but I was wondering if you happen to know whether DeepSORT tracker can be trained? I've modified the parameters of StrongSORT and managed to achieve slightly better results, but the ID assignment still isn't quite accurate. Therefore, I'd like to train the DeepSORT tracker if possible, as StrongSORT cannot be trained.

**Comment by caarmeecoorbii** [comment]
How can I train the reID model for DeepSORT with my own dataset?

**Comment by dyhBUPT** [comment]
FastReID is recommended.

--------------原始邮件--------------
发件人："caarmeecoorbii ***@***.***&gt;;
发送时间：2024年4月6日(星期六) 下午5:06
收件人："dyhBUPT/StrongSORT" ***@***.***&gt;;
抄送："dyhBUPT ***@***.***&gt;;"Comment ***@***.***&gt;;
主题：Re: [dyhBUPT/StrongSORT] Detections with own dataset (Issue #107)
-----------------------------------

 

 
How can I train the reID model for DeepSORT with my own dataset?
