### ISSUE TITLE
how to apply GSI to fairmot?

### ISSUE THREAD

**Issue by Cinderellashuang** [dyhBUPT/StrongSORT#11]
I have applied GSI in fairmot, but it worsens the original results. I wonder the threshold you set in GSI to obtain the IDF1 result of 74.2 mentioned in your paper . Thx for your great work!

**Comment by SmallGGgg** [comment]
> I have applied GSI in fairmot, but it worsens the original results. I wonder the threshold you set in GSI to obtain the IDF1 result of 74.2 mentioned in your paper . Thx for your great work!

Could you tell me the implementation details? Like what code to change. Thank you very much!
