### ISSUE TITLE
Using different datasets

### ISSUE THREAD

**Issue by TanganHitam1** [dyhBUPT/StrongSORT#110]
I want to use my datasets for the YOLOX detector and then test the DeepSORT / StrongSORT using a mp4 video format, what should I do?

**Comment by dyhBUPT** [comment]
1. First, you should prepare detection results using other repos, like ByteTrack, MMDetection.
2. Second, extract appearance features using other repos, like FastReID.
3. Third, prepare your detections and features in the DeepSORT format.
4. Finally, you can get the tracking results with this repo.

Please search for some related closed issues for details.

**Comment by TanganHitam1** [comment]
What if I want to direct tracking from .mp4 file using YOLOX as detector

**Comment by dyhBUPT** [comment]
It is not supported by this repo.

**Comment by zhaojunzhe123** [comment]
I think this is a good idea,it is helpful to do job with update the model between the sort model such as deepsort 、strongsort
