### ISSUE TITLE
AFLink & GSI order

### ISSUE THREAD

**Issue by TanganHitam1** [dyhBUPT/StrongSORT#111]
Is it a must to put AFLink first then GSI after that?, or what's the reason to put AFLink first before GSI?

**Comment by dyhBUPT** [comment]
Hi, that's because I think good association can benefit interpolation. You can also try to perform GSI first and check the difference.

**Comment by TanganHitam1** [comment]
What's the benefit of interpolation from a good association?, is it better if we get a better detection first using interpolation so we will get a better association

**Comment by dyhBUPT** [comment]
Assume we have one tracklet ranging from frames 1 to 10, and have another tracklet from 15 to 30.
AFLink can associate these two tracklets, ranging [1, 2, ..., 10, 15, 16, ..., 30]. Then GSI can generate the missing detections from frames 11 to 14.

**Comment by TanganHitam1** [comment]
Ahhh okay, that makes perfect sense, thank you so much
