### ISSUE TITLE
NSA Kalman filter

### ISSUE THREAD

**Issue by kai-dii** [dyhBUPT/StrongSORT#112]
Hi, Is the kalman_filter.py an implementation of the NSA Kalman filter?

**Comment by dyhBUPT** [comment]
Hi, yes, you can use NSA KF by setting `opt.NSA` as `True`.
https://github.com/dyhBUPT/StrongSORT/blob/d6a355480357989a9dd75a2a5e21713d517b1c35/deep_sort/kalman_filter.py#L148-L149
