### ISSUE TITLE
GSI and AFLink

### ISSUE THREAD

**Issue by caarmeecoorbii** [dyhBUPT/StrongSORT#114]
Hello,

Can you briefly explain how these modules improve the results of StrongSORT? I tested the code with my own dataset, and it only improves with AFLink in association, which makes sense, but GSI does not improve detection, it actually makes it worse.

Thank you,
Carme

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

For AFLink, it works when tracklets can be associated with pure motion patterns. If adding extra appearance information, it usually results in better performance.

For GSI, there exist two processes:
- First, you should check whether "linear interpolation" helps in your case. Sometimes, interpolation will worsen results when associations are not accurate enough. 
- Second, you should check whether "smoothing" helps. Sometimes, if the gt trajectories are complex, smoothing will not work.

If you still have problems, maybe you can share the visualization of your trajectories before and after GSI.

Best wishes.

**Comment by caarmeecoorbii** [comment]
Thank you very much. I have another question. In my dataset, I am dealing with soccer match data, the StrongSORT method fails to detect the ball in many frames since it is a very small element. Do you know how I could improve its detection?

**Comment by dyhBUPT** [comment]
Sorry, I'm not good at the detection task.

**Comment by Haoyalinglg** [comment]
strongsort的yolox+BoT的代码有吗

**Comment by dyhBUPT** [comment]
> strongsort的yolox+BoT的代码有吗

Please follow [Auxiliary Tutorials](https://github.com/dyhBUPT/StrongSORT/blob/master/others/AuxiliaryTutorial.md) for YOLOX and BoT.
