### ISSUE TITLE
help

### ISSUE THREAD

**Issue by chenshengyeah111** [dyhBUPT/StrongSORT#119]
others/generate_detections.py里面的 args.config_file = '../configs/DukeMTMC/bagtricks_S50.yml'是训练Reid获得的吗

**Comment by dyhBUPT** [comment]
It's the cfg used to train ReID model in FastReID.

**Comment by chenshengyeah111** [comment]
没有cfg的ReID咋处理

**Comment by dyhBUPT** [comment]
How did you train your ReID model?

**Comment by chenshengyeah111** [comment]
请问others/generate_detections.py里面的dir_out_det = '/data/dyh/results/StrongSORT/TEST/MOT20_YOLOX_nms.8_score.1_BoT-S50'放的是什么，怎么产生的呢

**Comment by dyhBUPT** [comment]
It's used to store the output detection features with the same format as in DeepSORT.

**Comment by chenshengyeah111** [comment]
dir_in_det = '/data/dyh/results/StrongSORT/Detection/YOLOX_ablation_nms.8_score.1
放的是什么，怎么产生的呢

**Comment by chenshengyeah111** [comment]
dir_in_det = '/data/dyh/results/StrongSORT/Detection/YOLOX_ablation_nms.8_score.1
放的是什么，怎么产生的呢,存放的是mot_evaluator.py目标检测以后的.json文件吗

**Comment by dyhBUPT** [comment]
It stores detections in "*.txt".
BTW, you don't need to pay much attention to this .py script. You just need to know the right input format of DeepSORT / StrongSORT, and write the script in your own style.

**Comment by chenshengyeah111** [comment]
请问为啥都在测试集上进行评估，为不在训练集上

**Comment by dyhBUPT** [comment]
it's for fairness.
