### ISSUE TITLE
Will codes for ECC be released?

### ISSUE THREAD

**Issue by HanGuangXin** [dyhBUPT/StrongSORT#12]
Thanks for your amazing work!

But now you have only provided results of ECC in json format. I was wondering whether the codes to get ECC results will be released?

Best wishes.

**Comment by dyhBUPT** [comment]
Hi, we have released our ECC code in "others/ecc.py" now and given a rough guidance in [Auxiliary tutorial](https://github.com/dyhBUPT/StrongSORT/blob/d59ce65ca95cb731b620e6f7965ab84336d57496/others/AuxiliaryTutorial.md).
Please contact me if you have any questions.

Best wishes.

**Comment by HanGuangXin** [comment]
Thanks very much! By the way, do you have the plan to release the code of UFK?
That's all right if the UFK code will not be released because UFK is used in GIAOTracker and not in StrongSORT.
It just may take me a lot of time to finish it by myself.

Anyway, thanks a lot :)

**Comment by dyhBUPT** [comment]
I'm sorry but we don't plan to release the code of GIAOTracker.
You can refer to [this blog](https://towardsdatascience.com/the-unscented-kalman-filter-anything-ekf-can-do-i-can-do-it-better-ce7c773cf88d) for some theoretical knowledge of UKF.
And the Python library [FilterPy](https://filterpy.readthedocs.io/en/latest/) would help.

Best wishes.

**Comment by HanGuangXin** [comment]
Appreciate it!
