### ISSUE TITLE
how to solve trajectory fragmentation in real-time mode

### ISSUE THREAD

**Issue by Edward-YS** [dyhBUPT/StrongSORT#120]
Hi,
I‘m wondering if there are any possibilities to use GSI in the real-time application.For example,can i use the GSI to interpolate as soon as i get a trace instead of using it until all results produce? Then every time the new trace produces i add it to the results set and update the interpolation processing. Pardon me if this is a fantastic idea.
Or do you have any suggestion to solve trajectory fragmentation in real-time mode?

**Comment by dyhBUPT** [comment]
It looks like an interesting question.
Maybe you can have a try for your idea. My concern is the performance of GSI may drop when the trajectory is too short. In this case, maybe you can switch to naive linear interpolation.
