### ISSUE TITLE
Will AFLink + GSI be effective for multi-target vehicle tracking?

### ISSUE THREAD

**Issue by heluhai** [dyhBUPT/StrongSORT#121]
hello
I want to use AFLink+GSI for multi-target vehicle tracking, but I don't know how to train my own parameters, can you tell me something about how to train?

**Comment by dyhBUPT** [comment]
Sorry for my late response.
For GSI, it doesn't need to train. You just need to tune the hyper-parameter `tau`.
For AFLink, please try this code:
https://github.com/dyhBUPT/StrongSORT/blob/master/AFLink/train.py
