### ISSUE TITLE
权重之类的数据下载可以放个百度云连接吗？没vpn,下载太慢了, 对国内的人不是很友好呀.....

### ISSUE THREAD

**Issue by DWendou** [dyhBUPT/StrongSORT#13]

**Comment by DWendou** [comment]
> 哈喽，感谢对我们工作的关注。 我们已经按照您的需求在REDAME内更新了百度网盘的链接。 祝您科研愉快，有问题随时联系。
> 
> ![image](https://user-images.githubusercontent.com/99722489/161257848-bb9d245a-8e2c-4f5a-afcd-64d1c8e815b4.png)

非常感谢，你们的工作非常的nice！

**Comment by dyhBUPT** [comment]
谢谢，祝科研顺利
