### ISSUE TITLE
Ground Truth detection for experiments evaluation on MOT 17

### ISSUE THREAD

**Issue by vovantuan1999a** [dyhBUPT/StrongSORT#14]
Hi Sir,

My name is Tuan, and I'm currently researching MOT.
I understand that the GT of the MOT 17 validation set is taken from FRCNN. But the evaluation of strongsort++ on set 17 uses YoloX detection. If so, can you please explain to me the evaluation of strongsort++ on Validation MOT 17? Should I use GT from FRCNN or YoloX? And how can I get GT validation MOT17 YoloX?

Thank you very much and Best Regards.

Tuan-Vovan

**Comment by dyhBUPT** [comment]
Hi Tuan,
Maybe I don't understand you problem clearly.
The GT of MOT17 is manually annotated, and you could use the gt.txt in the folder "MOT17-xx-FRCNN/gt" for validation. (surely you should extract the val half before computing the metrics)
And the detection results of StrongSORT++ is from the detector YOLOX, as in ByteTrack.

Maybe this would help?
Best wishes.

**Comment by vovantuan1999a** [comment]
Thank you very much; I'm complete clearly for validation.

However,  for the results testing on the MOT 20 test, yoloX or GT detection manually is used?

Best Regards
