### ISSUE TITLE
ECC error

### ISSUE THREAD

**Issue by su1517007879** [dyhBUPT/StrongSORT#16]
Thank you  for your great work. Could you tell me how to deal with following problems?
![image](https://user-images.githubusercontent.com/61399929/161895654-e8312632-0b88-49da-9835-1227cba0854b.png)

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

It seems like there exist some mistakes in your MOT20-05 dataset, i.e., "uncorrelated" image pairs.
By the way, it would be not necessary to run ECC on the MOT20 dataset because of its less camera movement.

Best wishes.
