### ISSUE TITLE
Eval on public detections? 

### ISSUE THREAD

**Issue by GerardMaggiolino** [dyhBUPT/StrongSORT#17]
Awesome work! Were there any evaluations done on public detections, to check performance degradation with a weaker detector? If not, are there plans to submit to MOT17/20 public? It appears OC-SORT, a heuristic based algorithm, is leading with MOT20 public. I'm curious if your addition of stronger appearance features will help given weaker bounding boxes.

**Comment by dyhBUPT** [comment]
Thanks for your appreciate.
It's really curious to test our algorithm on the public detections.
We would consider adding it in our future work.

Best wishes.
