### ISSUE TITLE
How to install apturl?

### ISSUE THREAD

**Issue by yanghaibin-cool** [dyhBUPT/StrongSORT#18]
@dyhBUPT First of all thank you for making this work open source.
when I run pip3 install -r requirements.txt,installation error:
![image](https://user-images.githubusercontent.com/72022193/162623310-8a6302da-4a90-47f1-ba00-3fee838a3ff0.png)
please how can i install apturl.

**Comment by dyhBUPT** [comment]
Hi, maybe you can ignore that package or install it by "sudo apt-get install apturl-common".

Best wishes

**Comment by yanghaibin-cool** [comment]
> Hi, maybe you can ignore that package or install it by "sudo apt-get install apturl-common".
> 
> Best wishes
First of all, thank you for your reply. 
Is it okay to use "sudo apt-get install apturl-common" instead of "pip3 install apturl" to install apturl in the current environment (such as StrongSort)?

**Comment by dyhBUPT** [comment]
I recommend that you can ignore this package first.
I'm a little confused now why this package is exported into the "requirements.txt"...
（>︿<）
