### ISSUE TITLE
feature重复进行归一化操作

### ISSUE THREAD

**Issue by long2double** [dyhBUPT/StrongSORT#19]
def _consine_istance(a,b,data_is_normalized=False) 内部进行了数据normalized，在执行track的update中也执行了一次normalized

在track的update中的normalized和track的__init__中的normalized是没有必要的？

**Comment by dyhBUPT** [comment]
您好，我觉得track.update中的归一化还是需要的，毕竟如果使用EMA的话，更新时候还是希望两个特征的尺度一致。不过调用 cosine_distance 时应该不需要做归一化。

祝好！
