### ISSUE TITLE
请问如何针对自己的数据集对AFLink进行训练？提供的根据MOT预训练好的模型能在别的数据用吗？

### ISSUE THREAD

**Issue by 5632515** [dyhBUPT/StrongSORT#20]
十分佩服您们的工作，感觉您是抱着热情和幽默进行的开发和撰写，具体问题如题

**Comment by dyhBUPT** [comment]
首先很开心您对我们工作的兴趣和认可。

关于AFLink，其实训练起来十分方便，我们在 AFLink/train.py 中提供了训练代码，其仅需依赖标注的 .txt 文件。您只需要准备好标注文件，修改目录即可。因此您可以尝试阅读一下源码并训练，遇到任何问题可以在这个issue下讨论。如果实在困难，我们会考虑更新对AFLink的训练说明。

我们没有在除MOT17和MOT20之外的其它数据集上测试过AFLink的性能。您也可以先尝试使用我们的预训练模型。

另外，这里我想温馨提示一下我认为的、目前AFLink的局限性，这在论文中也有部分提及。首先，其仅仅依赖运动信息进行全局关联，因此更适用于MOT17/20这种运动模式简单的场景，如果运动信息复杂，或许应该参考我们之前的工作[GIAOTracker](https://openaccess.thecvf.com/content/ICCV2021W/VisDrone/papers/Du_GIAOTracker_A_Comprehensive_Framework_for_MCMOT_With_Global_Information_and_ICCVW_2021_paper.pdf)。其次，AFLink仅可以处理missing association而不能解决false association问题，因此也带来了局限性。最后，由于模型和数据集较小，因此训练结果本身可能具有一定扰动。

我们鼓励任何对AFLink的质疑与改进。

祝好！

**Comment by 5632515** [comment]
谢谢百忙之中回复，本人只是个本科菜鸟，所以理解不够，谢谢啦

**Comment by dyhBUPT** [comment]
不客气，祝学业顺利~ ^.^
