### ISSUE TITLE
txt file

### ISSUE THREAD

**Issue by JuntongMeng** [dyhBUPT/StrongSORT#22]
hi
thanks for your work
I ran the demo of strong++, and the format of the generated txt file is different from the txt file required by MOTChallenge. How can I change the format of the submission?

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

But I think the format of the generated txt files is ok. Please read the requirements of MOTChallenge carefully. The only thing you need to do may be to add some trivial txts in the submitted zip file.

Please let me know whther you have solved it.
Best wishes.

**Comment by JuntongMeng** [comment]
Thank you for your reply
I'm a rookie, there may be something wrong with my understanding,
txt result after using AFlink and GSI
![image](https://user-images.githubusercontent.com/93414488/164950558-68d2a6c8-6682-4e9e-bf0d-069eaa511932.png)

But the format required by MOTCallenge is arranged by frame
![image](https://user-images.githubusercontent.com/93414488/164950563-09598b16-3203-4f59-a179-df601cd3e3c0.png)

**Comment by dyhBUPT** [comment]
Hi, the format of your txt results is ok.
You can visit the [offcial website](https://motchallenge.net/method/MOT=4710&chl=10) to download our submitted results for StrongSORT as a reference.

Best wishes.
