### ISSUE TITLE
请问如何将AFLink、GSI与其他跟踪器如ByteTrack进行结合？

### ISSUE THREAD

**Issue by lijinrun** [dyhBUPT/StrongSORT#23]
学长你好，我在下半年就要到北邮读研究生啦，之前在csdn翻译过您的这篇论文，有幸得到了您的点赞，我的本科毕设也是多目标跟踪这一方向，最近有个想法是将您在StrongSORT这篇论文中提出的AFLink、GSI等改进方法应用到ByteTrack中，不太了解怎么去实现，学长可以给些指导吗？

**Comment by dyhBUPT** [comment]
哈喽学弟，首先祝贺你即将来北邮就读研究生。

AFLink和GSI都是即插即用的方法，因此你可以参考strong_sort.py来调用相关函数。
但若将他们应用于ByteTrack，首先建议将其原本使用的线性插值关闭，否则难以发挥他们应有的作用。

祝好~

**Comment by lijinrun** [comment]
好的谢谢学长，我刚刚给您在论文中留的邮箱发了个邮件。
