### ISSUE TITLE
Evaluating on MOT17 and MOT20

### ISSUE THREAD

**Issue by navaravan** [dyhBUPT/StrongSORT#27]
Hi @YunhaoDu @dyhBUPT 
Thanks for sharing this amazing work
How can we evalutate the StrongSort tracker on MOT17 and MOT20 dataset. Can you list the steps?

**Comment by dyhBUPT** [comment]
Hi, thanks for your requests.

We have update the README file to give a guide to evaluate the tracking results on the MOT17-val set.
![image](https://user-images.githubusercontent.com/99722489/167144617-fbebe6bb-4a14-4372-b797-33df258c2e38.png)

Please feel free to contact me if you have any questions on it.
Best wishes.

**Comment by navaravan** [comment]
Hi @dyhBUPT 
Thanks for updating the Readme
