### ISSUE TITLE
Customising For different detectors

### ISSUE THREAD

**Issue by navaravan** [dyhBUPT/StrongSORT#28]
Hi @YunhaoDu @dyhBUPT 

>Thanks for sharing the works.
>Can this tracker be used with different detectors like YoloX?
>When I go through your code I can see you are loading detection's from a numpy file, I can see you are loading bbox, conf and features, whether features are required by your tracker?
>Can you list the steps in brief for configuring this tracker with different detectors and what are the inputs required by the tracking module from the detector?

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

The default detector in StrongSORT is YOLOX. You can try any other detectors.
For this purpose, you should prepare the npy file which contains the detection results and features.
It follows the same format as in [DeepSORT](https://github.com/nwojke/deep_sort).
To be specific, each row represents one bbox as:
> frame_id, -1, x, y, w, h, confidence, -1, -1, -1, features

That is, 10 dimensions for box information and the other dimensions (2048 in StrongSORT) for features.
The entire npy is a Nx2058 matrix for each video.

So, if you want to try other detectors, you should prepare the detection results and their features by your self. 
Maybe the [Auxiliary tutorial](https://github.com/dyhBUPT/StrongSORT/blob/d59ce65ca95cb731b620e6f7965ab84336d57496/others/AuxiliaryTutorial.md) can also help you.

Best wishes.

**Comment by navaravan** [comment]
Hi @dyhBUPT 
Thanks for the reply
How StrongSORT is actually different from DeepSORT, I can see similar python codes inside DeepSORT repo also.

**Comment by dyhBUPT** [comment]
You're right. We build the StrongSORT based on the repo of DeepSORT.
Therefore, the most of our codes are the same as DeepSORT.
Our contributions are adding some optimization techniques.
We recommend you reading [our paper](https://arxiv.org/abs/2202.13514) for details.

Best wishes.

**Comment by navaravan** [comment]
Hi @dyhBUPT 
Thanks for the reply
Please correct me if I'm wrong, StrongSORT uses detection results from YOLOX and Features generated for the corresponding detection from FastReID?

**Comment by dyhBUPT** [comment]
You're right, but it's just the small parts of the contributions of our work.

**Comment by navaravan** [comment]
Hi @dyhBUPT 
Thank you for your responses.
