### ISSUE TITLE
后处理

### ISSUE THREAD

**Issue by CompliceU** [dyhBUPT/StrongSORT#3]
@dyhBUPT 你好，你的工作确实有很大的新意，但是不知道是不是可以理解为在别的跟踪器完成跟踪后，使用AFlink和GSI尽兴跟踪轨迹的优化呢

**Comment by dyhBUPT** [comment]
感谢对我们工作的关注。
您理解的是正确的，本工作中的AFLink和GSI目的就是提出即插即用且代价较小的算法，从而应用于各种跟踪器。所以可以理解为后处理优化算法。建议与我们之前在ICCV2021 workshop中的工作GIAOTracker对比阅读，两者在整体思想上很相似。
https://arxiv.org/abs/2202.11983

**Comment by CompliceU** [comment]
> 感谢对我们工作的关注。 您理解的是正确的，本工作中的AFLink和GSI目的就是提出即插即用且代价较小的算法，从而应用于各种跟踪器。所以可以理解为后处理优化算法。建议与我们之前在ICCV2021 workshop中的工作GIAOTracker对比阅读，两者在整体思想上很相似。 https://arxiv.org/abs/2202.11983
好的，感谢你们的开源工作

**Comment by CompliceU** [comment]
@dyhBUPT 好的 非常感谢你们的开源工作

**Comment by dyhBUPT** [comment]
不用客气，科研顺利！

**Comment by CompliceU** [comment]
@dyhBUPT 不知道你们有开源之前GIAOTracker这项工作吗

**Comment by dyhBUPT** [comment]
抱歉，因为是参加竞赛，因此GIAOTracker并没有开源计划。

**Comment by CompliceU** [comment]
@dyhBUPT 好的 哈哈哈 我看到其中用UKF的工作 觉得不错 想学习学习

**Comment by dyhBUPT** [comment]
UKF代码实现层面类似Kalman Filter，理论学习建议参考博客：https://towardsdatascience.com/the-unscented-kalman-filter-anything-ekf-can-do-i-can-do-it-better-ce7c773cf88d

**Comment by lhfabc9** [comment]
> UKF代码实现层面类似Kalman Filter，理论学习建议参考博客：https://towardsdatascience.com/the-unscented-kalman-filter-anything-ekf-can-do-i-can-do-it-better-ce7c773cf88d

你好，如果可以我想问一下你们运用UKF有修改原来的运动方程吗？

**Comment by dyhBUPT** [comment]
> > UKF代码实现层面类似Kalman Filter，理论学习建议参考博客：https://towardsdatascience.com/the-unscented-kalman-filter-anything-ekf-can-do-i-can-do-it-better-ce7c773cf88d
> 
> 你好，如果可以我想问一下你们运用UKF有修改原来的运动方程吗？

关于UKF的实现，可以选择多种运动模型，包括CTRV、CTRA等，我们在GIAOTracker中使用的是CTRA。
但KF、UKF这类传统算法的麻烦在于对超参数较为敏感，因此您确实对其需要精心设计。我们之前在另一个场景使用UKF时出现过“非正定”问题，最后貌似是通过适当调整超参数解决的，有点忘记了。

另外温馨提示一点，我们在StrongSORT工作中也尝试过在MOT17中应用UKF，但没有获得有效的提升，原因可能是该数据集中目标的运动模型并不像无人机视频那么复杂。经验仅供参考。

祝好。

**Comment by lhfabc9** [comment]
好的，感谢回答！

**Comment by lhfabc9** [comment]
> 

不好意思，我还想问一个问题，就是如果我仅仅用yolo之类的检测器检测，CTRA这样的模型是不是用不了啊，角度加速度之类 的参数无法获得

**Comment by dyhBUPT** [comment]
> > 
> 
> 不好意思，我还想问一个问题，就是如果我仅仅用yolo之类的检测器检测，CTRA这样的模型是不是用不了啊，角度加速度之类 的参数无法获得

角度/速度/加速度可以利用过去N帧的位置估算出来

**Comment by lhfabc9** [comment]
> > > 
> > 
> > 
> > 不好意思，我还想问一个问题，就是如果我仅仅用yolo之类的检测器检测，CTRA这样的模型是不是用不了啊，角度加速度之类 的参数无法获得
> 
> 角度/速度/加速度可以利用过去N帧的位置估算出来
还是实现不了，冒昧问一下这种估算有例子可以参考吗？

**Comment by dyhBUPT** [comment]
> > > > 
> > > 
> > > 
> > > 不好意思，我还想问一个问题，就是如果我仅仅用yolo之类的检测器检测，CTRA这样的模型是不是用不了啊，角度加速度之类 的参数无法获得
> > 
> > 
> > 角度/速度/加速度可以利用过去N帧的位置估算出来
> > 还是实现不了，冒昧问一下这种估算有例子可以参考吗？

可以自己网上搜一下
