### ISSUE TITLE
FPS calculation

### ISSUE THREAD

**Issue by navaravan** [dyhBUPT/StrongSORT#30]
Hi @dyhBUPT @YunhaoDu 
While going through the repo I can see you have calculated the FPS on MOT17 dataset, can you list down the steps to calculate FPS on MOT17 dataset?

**Comment by dyhBUPT** [comment]
Hi, I just use the package "[datetime](https://docs.python.org/3/library/datetime.html)" to compute the running time, and calculate the FPS manually.

Best wishes.

**Comment by navaravan** [comment]
Hi @dyhBUPT 
The FPS column present in the table 4 and 5 are the ones with detector plus feature extraction plus tracker module or only tracker module?

**Comment by dyhBUPT** [comment]
Hi, the FPS is calculated with "feature extraction" + "Camera Motion Compensation (ECC)" + “Tracking”.
The detector is not included following the protocol of [MOTChallenge](https://motchallenge.net/).

Best wishes.

**Comment by navaravan** [comment]
Hi @dyhBUPT 
Thanks for the clarification
