### ISSUE TITLE
StrongSORT with custom Object Detector

### ISSUE THREAD

**Issue by leduy99** [dyhBUPT/StrongSORT#32]
Hi, I'm currently handling the MOT problem in my research assignment, It's clear that StrongSORT is now top 1 ranking for MOT17 and MOT20 dataset so I wanna give it a try. I have trained a well yolov5 detector and used smoothly with DeepSORT. So I wonder if I can custom this repo to attach my yolov5 detector with the StrongSORT algo just like with DeepSORT?
Thanks :D

**Comment by dyhBUPT** [comment]
Yes, you can surely use your own detector and features. You just need to prepare following the [instruction](https://github.com/dyhBUPT/StrongSORT#datamodel-preparation).
And for a different detector, some parameters tuning (e.g., detection confidence threshold) would be needed. 

If you want to use a stronger ReID model to extract appearance features, the [Auxiliary tutorial] may help.

We will appreciate it if you will share the ablation study on YOLOv5, or tell us whether the components in StrongSORT work well.
Best wishes.
