### ISSUE TITLE
How to run on test?

### ISSUE THREAD

**Issue by amitgalor18** [dyhBUPT/StrongSORT#36]
Hi,
Thank you very much for sharing your work!
I use the AFLink with a different tracker, and it works well when I run it on the train dataset but when I try to run on the test dataset I get an error in `LinkData`. The `initialize` function in the `dataset.py` script runs on the **train** sequences regardless of the "mode" input, and also looks for gt files which aren't available for test sequences.
Which parts do I need to change if I want to run AFlink on a test dataset?

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.
For AFLink, if you want to apply it to the tracker, please set the param `root` of `LinkData` as `''`, as in https://github.com/dyhBUPT/StrongSORT/blob/968848035c603732ad66a7cc8711a7b5b622f814/strong_sort.py#L20

Please let me know if this helps.

BTW, we would appreciate it if you can tell us what tracker you apply AFLink to.
Best wishes.

**Comment by amitgalor18** [comment]
Thank you very much, it worked.
I'm working on a modified version of TransCenter and try various features for improvement, so I also use AFLink.
