### ISSUE TITLE
multi OBJECT tracking

### ISSUE THREAD

**Issue by DoubleRedX** [dyhBUPT/StrongSORT#37]
I am working on a project which needs to track multi objects. These objects are not person, and  the tracking result is not well. So I am considering how can I train the strong sort to track the object (not person)?

**Comment by LamnouarMohamed** [comment]
I didn't go deeper on this repository but I have seen the paper of StrongSORT they have base on Object Detection on Yolox-x, I think you can train Yolox-x on yours dataset, **_be careful if they did modify yolox-x before integrate to StrongSORT_** (Attention, check this condition before training)
