### ISSUE TITLE
about visdrone

### ISSUE THREAD

**Issue by wsw321** [dyhBUPT/StrongSORT#38]
when I pass track results files to  visdrone official eval code, and run "task4a" in evalMOT.m, some error occured :
![image](https://user-images.githubusercontent.com/41329847/180779049-9f7da09a-050a-4a96-89de-22b3755c605e.png)
do you know how to solve this problem?

**Comment by dyhBUPT** [comment]
Hi, we should only talk about StrongSORT and GIAOTracker in this repo.
For the question for the VisDrone evaluation code, please contact with the its organizer.

Best wishes.
