### ISSUE TITLE
How does GiaoTracker makes 

### ISSUE THREAD

**Issue by wsw321** [dyhBUPT/StrongSORT#40]
Hi,Thanks for your wonderful work!
How does GiaoTracker make ReID datasets based on MOT datasets？

best wishes.

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.
We've presented the details of establishing the ReID dataset in our paper in Section 4.2.
Please refer to it.

Best wishes.

**Comment by wsw321** [comment]
Thank you for your reply, I'll read it.

**Comment by dyhBUPT** [comment]
I've just created a repo of GIAOTracker: https://github.com/dyhBUPT/GIAOTracker.
So, you can also submit your issues in that repo.

Best wishes.
