### ISSUE TITLE
How can I get this txt format result in a video format?

### ISSUE THREAD

**Issue by iamdami** [dyhBUPT/StrongSORT#43]
Hi. Thank you for your amazing work!

I followed your instructions and got the txt format result.
I want to view this result in a video format like [this](https://motchallenge.net/method/MOT=4710&chl=10).
Do I have to summit a zip file to MOT Challenge official site or is there another way?

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

You don't have to submit the results for a video output.
You can try to write a script to visualize the tracking results, and `opencv-python` is recommended. 
It's not so hard, please try it by yourself.

Best wishes.

**Comment by iamdami** [comment]
Thanks for the quick feedback.
I'm gonna try it out :)
