### ISSUE TITLE
implementation with detection model

### ISSUE THREAD

**Issue by prsnkmr** [dyhBUPT/StrongSORT#44]
is there any manual how to run on test videos,  and is there any implementation to integrate strongsort++ with any object detetction model like yolov5 . if there is please share it will be helpfiul.

**Comment by dyhBUPT** [comment]
Hi, we've privided an [Auxiliary Tutorial](https://github.com/dyhBUPT/StrongSORT/blob/master/others/AuxiliaryTutorial.md), which gives a coarse guide to run StrongSORT on other datasets, with your own detections and features.
I hope this will helps.

Best wishes.

**Comment by kadirnar** [comment]
> test videolarında nasıl çalıştırılacağına dair herhangi bir kılavuz var mı ve yolov5 gibi herhangi bir nesne algılama modeliyle strongsort++ entegre etmek için herhangi bir uygulama var mı? varsa paylaşın lütfen yardımcı olacaktır.

Hi @prsnkmr ,

Yolov5-Pip + StrongSort : https://github.com/kadirnar/yolov5-strongsort

**Comment by dyhBUPT** [comment]
> 

Hi, please consider citing our paper and repo, thanks~

**Comment by dyhBUPT** [comment]
> > test videolarında nasıl çalıştırılacağına dair herhangi bir kılavuz var mı ve yolov5 gibi herhangi bir nesne algılama modeliyle strongsort++ entegre etmek için herhangi bir uygulama var mı? varsa paylaşın lütfen yardımcı olacaktır.
> 
> Hi @prsnkmr ,
> 
> Yolov5-Pip + StrongSort : https://github.com/kadirnar/yolov5-strongsort

Hi, please consider citing our paper and code, thansk~

**Comment by kadirnar** [comment]
Thanks for your feedback, I edited it.
