### ISSUE TITLE
train

### ISSUE THREAD

**Issue by SongHfei** [dyhBUPT/StrongSORT#45]
how to train a tiny flops(10M flops) tracking model.?

**Comment by dyhBUPT** [comment]
you mean a detector? reid model? maybe this is beyond the scope of our repo.

**Comment by SongHfei** [comment]
> 我已经用yolov7训练了一个检测器.现在想训练一个更小的跟踪模型.不是很熟悉 没找到有详细的训练教程和参数细节

**Comment by dyhBUPT** [comment]
so what do you mean of the `tracking model`?
The StrongSORT takes detections with features as input, and doesn't need additional training.

**Comment by SongHfei** [comment]
emmmmmm,我先学习一下 理清楚了再来提问 不好意思.osnet_x0_25_market1501

**Comment by dyhBUPT** [comment]
That's ok. Thanks for your interest in our work.
Best wishes~

**Comment by SongHfei** [comment]
额 打扰了 还请指教
https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet
或者https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet中。
在演示代码里需要加载两个权重文件,一个是检测器的yolov7或者yolov5.
还有一个权重文件是strong-sort-weights =osnet_x0_25_market1501.pt!!!..
我想知道怎么样训练一个下面这个模型,我想自己训练一个更加轻量级的reid跟踪模型.但我在您的git里没有找到相关训练的资料

**Comment by dyhBUPT** [comment]
Hi, they are not the official codes of our work.
Maybe you should sumbit an issue in these repos.
