### ISSUE TITLE
Matching boxes for 2 people issue

### ISSUE THREAD

**Issue by botasb** [dyhBUPT/StrongSORT#46]
Hi. 
Great job!
Just a comment (no idea if this is an "issue" really...). I am tracking people with a combination of Yolo + StrongSORT. At some point I have 2 people, properly tracked until that moment, but their bounding boxes seems to overlap in one frame. At that point, one of them (strangely, the one not occluded at all and with the lowest trackId) losses his box and trackId. A few frames later, once not overlapping, he is assigned a new box and trackId. 
Any idea how to approach this?

Thanks again!

**Comment by dyhBUPT** [comment]
Hi, it seems that occlusion contaminates the appearance features of these people. Maybe you can just drop those features with high occlusion? (refer to: Li F, Wang Z, Nie D, et al. Multi-camera vehicle tracking system for AI City Challenge 2022)
Or, can you give a visualization example to help me better understand your problem?

Best wishes.
