### ISSUE TITLE
卷积核

### ISSUE THREAD

**Issue by gw0522** [dyhBUPT/StrongSORT#49]
您好请问在 aflink部分为什么时间模块是使用7*1卷积 融合模块使用1*3卷积 请问是出于什么考虑呢 常见的卷积核一般不都是7*7和3*3的吗

**Comment by dyhBUPT** [comment]
It's for extracting information on corresponding dimensions, i.e., 7x1 for temporal dimension, 1x3 for [f,x,y] dimension.
You can also try other structures.
You're welcomed to share your experiment results.

Best wishes.
