### ISSUE TITLE
aflink temporalblock

### ISSUE THREAD

**Issue by gw0522** [dyhBUPT/StrongSORT#50]
Hello, may I ask if the initial value of X in the time module of AFLINK code is [2,1,30,3]? Is it correct for me to understand 2 as Bach 30 as input 30 frames and 3 as F, X and Y? How should I understand 1? If not, what do these four parameters represent

**Comment by dyhBUPT** [comment]
Hi, you're right, the dimension of the input of AFLink is [B, 1, 30, 3]. 
The "1" just acts as the "channel dimension" like common computer vision models. For example, in image classification, the "1" will change to "3" which represents the RGB channels.

Best wishes.
