### ISSUE TITLE
Multi camera tracking

### ISSUE THREAD

**Issue by faizan1234567** [dyhBUPT/StrongSORT#51]

**Comment by faizan1234567** [comment]
Thanks for the nice work, is this support multi camera tracking? I am integrating yolov5 with strong sort, I want to know if it is possible to track an object across multiple cameras with unique id.

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

StrongSORT (and other common MOT methods) only support single-camera tracking.
For cross-camera tracking, the simplest way is:
1. generate single-camera tracklets using StrongSORT.
2. associate these tracklets across cameras with appearance features and spatio-temporal constraints.

Best wishes.

**Comment by dyhBUPT** [comment]
the simplest way is to use the same appearance features as in step 1.
Maybe you should refer to some MCMOT works.
For example: https://openaccess.thecvf.com/content/CVPR2022W/AICity/html/Yang_Box-Grained_Reranking_Matching_for_Multi-Camera_Multi-Target_Tracking_CVPRW_2022_paper.html
