### ISSUE TITLE
evaluate the result on MOT17-test set

### ISSUE THREAD

**Issue by besubtle** [dyhBUPT/StrongSORT#52]
Hi, thanks for your great work!

what  I  need to do if I wanna evaluate the result on MOT17-test set ? I can't find the `gt.txt` file of  MOT17-test. 
should I sign up in the MOT challenge to submit my result on MOT17-test set first, then I can get all the  metric value?

thank you very much!

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

You're right that you should submit the testset results to MOTChallenge website then you will get the metric value.

Best wishes.
