### ISSUE TITLE
Track objects skipping detections

### ISSUE THREAD

**Issue by ignaciomendizabal** [dyhBUPT/StrongSORT#53]
Hi, thank you for your work. I would like to know if it is possible to keep track of objects without updating the detections every frame. I have an object detector that runs every 8 frames, so I'd like to keep track of objects during the remaining 7 frames without detections.
Thanks in advance.

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

A low frame-rate detection is ok, but the tracking accuracy will drop. You can have a try.
You may need some modifications on codes and hyper-parameters.

Best wishes.

**Comment by ignaciomendizabal** [comment]
Thank you, I'll check the code and add the changes to this issue if it works.
