### ISSUE TITLE
如何训练自己的跟踪数据集

### ISSUE THREAD

**Issue by JustinLibo** [dyhBUPT/StrongSORT#54]
您好！我目前正在学习目标跟踪，想整合yolov7和StrongSORT的代码查看检测跟踪效果；

我想要检测追踪的目标是在一个场景下不停翻转的魔方，跟踪在视频中出现的左右手和魔方；

想请问下目前我已经有了在yolov7训练结束的训练权重，是否还需要针对性的使用StrongSORT对数据集进行特征提取训练（因为我注意到论文中的训练主要针对于行人重识别），以获得权重文件？如果需要，请问该如何训练呢，谢谢您！

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

In your case, I recommend you to train a appearance model. You can use the [FastReID](https://github.com/JDAI-CV/fast-reid) to implement it.
Of course, you can also use its pretrained model first to check the tracking performance.

Best wishes.
