### ISSUE TITLE
Would you please provide code snippet how the AFLink used on fairMOT ?

### ISSUE THREAD

**Issue by ssbilakeri** [dyhBUPT/StrongSORT#56]

**Comment by dyhBUPT** [comment]
Hi, just run like this:
https://github.com/dyhBUPT/StrongSORT/blob/efc79c21182736a8a21c32f4f2114a57fc812dac/strong_sort.py#L36-L45
, where `path_save` is the path of the FairMOT results.

Please change `thrT` to (-10,30) and `thrP` to 0.10.

**Comment by ssbilakeri** [comment]
Thank you very much for the quick response.

Can you please clarify to me on what basis you chose values for thrT=(0,
30),   thrS=75,  thrP=0.10 ?

If we change the tracker,  do we need to fine tune these values ?

Thanks & Regards
Shavantrevva.

**Comment by dyhBUPT** [comment]
Hi, we choose these values based on experiment results. 
We just tested AFLink on CenterTrack, FairMOT, TransTrack, and these changes have better results.
