### ISSUE TITLE
关于KITTI榜单上的StrongSort++

### ISSUE THREAD

**Issue by 1145284121** [dyhBUPT/StrongSORT#57]
您好，我看到kitti榜单上有个strongsort++的排行，代码链接指向这里，请问是最近官方最近更新了KITTI的实验嘛？
<img width="763" alt="屏幕截图_20221221_110931" src="https://user-images.githubusercontent.com/41956449/208811614-77a7f125-11f5-4067-a93d-2cd91325f82b.png">

**Comment by dyhBUPT** [comment]
Yes, it's submitted by us. We conduct experiments on KITTI based on the detections from PermaTrack. 
But the code for KITTI is not yet public.

**Comment by 1145284121** [comment]
> Yes, it's submitted by us. We conduct experiments on KITTI based on the detections from PermaTrack. But the code for KITTI is not yet public.

感谢回复，期待开源

**Comment by yiding-wang1** [comment]
您好，我想在KITTI数据集上复现本方法。请问是否方便提供PermaTrack上的检测结果文件，或生成相应检测结果的guidance？
