### ISSUE TITLE
How did you generate the plot shown in paper figure 4? 

### ISSUE THREAD

**Issue by ssbilakeri** [dyhBUPT/StrongSORT#63]
Please provide the code to plot figure 4

**Comment by dyhBUPT** [comment]
It's drawn by PPT

**Comment by ssbilakeri** [comment]
Is that plot based on track results? If so can you provide code snippet for
the same

**Comment by dyhBUPT** [comment]
I'm sorry, but it doesn't correspond to any tracking results.
