### ISSUE TITLE
Why do the results get worse when I use NSA Kalman filtering

### ISSUE THREAD

**Issue by epns** [dyhBUPT/StrongSORT#65]
I simply modified the code in Kalman.py in my code and the `new_track.score` parameter is passed in `std = [(1 - new_track.score) * x for x in std]`.
But MOTA, HOTA and IDSW all get worse except IDF1.

**Comment by dyhBUPT** [comment]
NSA will change the `std` parameters of Kalman Filter. It's not guaranteed to work in every scenario.
