### ISSUE TITLE
Using StrongSORT with custom detector and without appearance features

### ISSUE THREAD

**Issue by jokober** [dyhBUPT/StrongSORT#68]
I'm planning on using StrongSORT to detect flying birds which are often really small and change appearance fast due to wingflaps.

I am now wondering if it is possible to use StrongSort with my custom detector and without appearance features only having detection bounding boxes and confidence.

**Comment by dyhBUPT** [comment]
Hi, for your case, you can try to discard the usage of appearance features and only use the motion information.
For this end, you should modify the codes.

You can also try [ByteTrack](https://github.com/ifzhang/ByteTrack) or [OC-SORT](https://github.com/noahcao/OC_SORT), which don't need appearance features.

Best wishes.
