### ISSUE TITLE
KeyError: 'MOTChallenge\\MOT17\\train\\MOT17-02-FRCNN'

### ISSUE THREAD

**Issue by buyi6666** [dyhBUPT/StrongSORT#69]
Thank you for your great work !

When I run  `strong_sort.py MOT17 val --BoT --ECC --NSA --EMA --MC --woC` , it displays
 ```
StrongSORT-master\deep_sort\track.py", line 141, in camera_update dict_frame_matrix =opt.ecc[video]
KeyError: 'MOTChallenge\\MOT17\\train\\MOT17-02-FRCNN'
```
Why does it happen ?

**Comment by dyhBUPT** [comment]
Duplicate issue with #70, so I will close it.
