### ISSUE TITLE
This is a very good code! How do I train my data set?

### ISSUE THREAD

**Issue by PiBigStar5712** [dyhBUPT/StrongSORT#76]
I wanted to use the YOLOV5 version of the target tracking framework because I had trained my data set with it. So can I simply replace the YOLOV7 file in this project with V5 to use directly? 
Then I don't know how to train the Strongsort, and if I need to track something different from what I trained it to do, then its reID will change wildly. If I need to retrain the Strongsort, how do I make the data set?
Looking forward to your reply！

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

To apply StrongSORT to your dataset & detector, you just need to prepare the detection results with appearance features.
The main tracking algorithm of StrongSORT doesn't need any training.

Furthermore:
- you may need to prepare the CMC results (e.g. ECC) if you need them.
- you may need to train the AFLink model if you need it.

Best wishes.

**Comment by PiBigStar5712** [comment]
> Hi, thanks for your interest in our work.
> 
> To apply StrongSORT to your dataset & detector, you just need to prepare the detection results with appearance features. The main tracking algorithm of StrongSORT doesn't need any training.
> 
> Furthermore:
> 
> * you may need to prepare the CMC results (e.g. ECC) if you need them.
> * you may need to train the AFLink model if you need it.
> 
> Best wishes.

我是一名移动机器人领域的初学者，对于深度学习方面不是很了解，现在有一些问题想咨询你。

①StrongSort作为DeepSort的升级版，如果我使用自己的数据集，跟踪的目标不是行人或者车辆而是其他物体的话（DeepSort的原版主要针对的是行人和车辆的重识别），是否还需要像DeepSort一样重新训练reID？

②StrongSort的推理部分是使用的什么？我在此项目中尚未看到YOLO等目标识别的代码。是需要自己接入目标检测的代码吗，如果是，应该如何在这个项目中插入目标检测的模块，能否给一个说明文档。

③对于无外观链路模型（AFLink），按我前面所述，我打算使用自己的数据集做目标跟踪的话，是否需要重新训练？如果需要的话，我应该怎么训练，数据集所需要的格式是什么，能否提供一份详细的教程
④如果使用自己的数据集，累积匹配特征(CMC)是否也同③一样需要重新训练，如果是的话，我应该如何操作

万分感谢你的来信，也许我上述这些问题对于你来说是比较愚蠢低级的问题。但我还是恳求你能够为我解惑。

**Comment by dyhBUPT** [comment]
Hi,

① Yes, if you want a higher accuracy, you need to retrain the ReID model.

② Yes, StrongSORT takes detections with features as input, therefore you need to provide the "detection+feature" files. Each row represents a detection, the dimension 0~9 is the bbox information, and dimension 10+ are features.

③ Yes, you need to retrain AFLink using the provided codes "https://github.com/dyhBUPT/StrongSORT/blob/master/AFLink/train.py", which is based on the gt format of MOT17. You can also don't use AFLink at first.

④ Yes, you need to prepare your own CMC results. The codes "https://github.com/dyhBUPT/StrongSORT/blob/master/others/ecc.py" will help. which is based on the MOT17 dataset.

Best wishes.
