### ISSUE TITLE
About the illustrations in the paper

### ISSUE THREAD

**Issue by godHhh** [dyhBUPT/StrongSORT#78]
Congratulations on your accepted paper！
I would like to ask about the effect comparison chart on the second page of your paper, was it generated using python code or drawing software such as origin? I'm a newbie in this field, I hope you can give me some advice!
best wish!

**Comment by dyhBUPT** [comment]
Thank you~

The figure is drawn using Python, and the package `matplotlib.patches` plays an important role.

Best wishes.

**Comment by godHhh** [comment]
I've seen many papers using this comparison chart, is there an open source toolkit that can be used? I'm a little lazy and don't want to reinvent the wheel, hhh. 
Best wishes.

**Comment by dyhBUPT** [comment]
I'm not sure. You can try to find it~

**Comment by godHhh** [comment]
Okay, thank you very much~
