### ISSUE TITLE
关于跟踪的特征提取部分的训练

### ISSUE THREAD

**Issue by 666cgl666** [dyhBUPT/StrongSORT#79]
项目中跟踪的特征提取部分，我想训练自己的目标，请问该怎么训练

**Comment by dyhBUPT** [comment]
Hi, please refer to [FastReID](https://github.com/JDAI-CV/fast-reid) to train your own reid model.
Maybe our provided [Auxiliary tutorial](https://github.com/dyhBUPT/StrongSORT/blob/master/others/AuxiliaryTutorial.md#3-how-to-generate-features) will help.

Best wishes.
