### ISSUE TITLE
Code for get detection+features

### ISSUE THREAD

**Issue by vovantuan1999a** [dyhBUPT/StrongSORT#8]
Hello Sir,

My name is Tuan, I'm currently researching MOT.
Can you give me the code for extract detection+features in part 2 of Data & Model Preparation?

Thank you and best regards,
Tuan

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

We use the yolox code in [ByteTrack](https://github.com/ifzhang/ByteTrack) to generate detections and use the [FastReID](https://github.com/JDAI-CV/fast-reid) framework to extract features.
You can easily follow them to generate detection+features.

Please contact me if you have any questions.
Best wishes.

**Comment by vovantuan1999a** [comment]
Thank you for your response.

Best Regards,

**Comment by vovantuan1999a** [comment]
Hi Sir, I try to flow the ByteTrack and FastReId to get data prepared for the input of StrongSort but it's hardcore.

Please Can give me the pipeline code to get input of StrongSort?
Thank you and Best Regards.

**Comment by dyhBUPT** [comment]
As for your question, we give a rough guidance to generate detections and features now in [Auxiliary tutorial](https://github.com/dyhBUPT/StrongSORT/blob/d59ce65ca95cb731b620e6f7965ab84336d57496/others/AuxiliaryTutorial.md), and some code for reference.
But you till need to write some simple scripts yourself.

Please contact me if you have any questions
Best wishes. ^.^

**Comment by vovantuan1999a** [comment]
Thank you and Best Regards.
