### ISSUE TITLE
Detection model weights

### ISSUE THREAD

**Issue by IrinaMonaEpure** [dyhBUPT/StrongSORT#82]
Hi! I am trying to run your code on MOT17 and MOT20 with detection files generated with bytetrack_ablation.pth.tar from the [ByteTrack model zoo](https://github.com/ifzhang/ByteTrack#model-zoo) as you exemplify in [step 2 of the auxiliary tutorial](https://github.com/dyhBUPT/StrongSORT/blob/master/others/AuxiliaryTutorial.md#2-how-to-generate-detections). Are those the same detection model weights you used for your experiments? Otherwise, could you provide the weights of the detection model(s) you used to generate detections for MOT17 and MOT20?

**Comment by dyhBUPT** [comment]
Hi, we use the exactly the same weights as ByteTrack.
That's, 
- For MOT17-val: `bytetrack_ablation.pth.tar`
- For MOT17-test: `bytetrack_x_mot17.pth.tar`
- For MOT20-test: `bytetrack_x_mot20.pth.tar`
