### ISSUE TITLE
Virtual environment config?

### ISSUE THREAD

**Issue by NicklasVraa** [dyhBUPT/StrongSORT#83]
Is it possible for you to upload the exact config for the virtual environment, in which you ran the code? What version of numpy, scipy, torch, etc., where you using?

Many deprecation errors (not warnings) are being raised when we try to run the code as instructed in the readme.

**Comment by dyhBUPT** [comment]
Hi, the version of main packages are as follows:
- numpy==1.19.5
- opencv-python==4.5.4.58
- scipy==1.5.4
- scikit-learn==0.19.2
- torch==1.9.0

Will this help you?

**Comment by milad-goudarzi** [comment]
Hi. I'm also getting the error of missing yolov5 module. I don't wanna use yolov5 because I already completed my project with yolov8 and DeepSORT and just want to replace DeepSORT with StrongSORT. What can I do?

**Comment by dyhBUPT** [comment]
Hi, `opts` is not a module, it is here:
https://github.com/dyhBUPT/StrongSORT/blob/master/opts.py

Therefore, maybe the reason is that you use a wrong system path to run the code, and the `opt.py` cannot be found in your path. Please try to add it to your path.
