### ISSUE TITLE
Questions about ECC

### ISSUE THREAD

**Issue by flag16** [dyhBUPT/StrongSORT#87]
Hi, I have modified the functions to_tlwh and to_xyah. When I use --ECC I don't get the result, all targets are not confirmed. But when I don't use ECC everything works fine. Do you know why this is?

**Comment by dyhBUPT** [comment]
Sorry, I have no idea about it. Maybe you should debug to find out the error.

**Comment by flag16** [comment]
Well, thank you for your prompt reply
