### ISSUE TITLE
Strong sort tracks a different object based on another detection.

### ISSUE THREAD

**Issue by Nuwan1654** [dyhBUPT/StrongSORT#88]
Here is a small clip of the overlayed tracks and detections :
https://drive.google.com/file/d/1lF7uBxWVE4pe4p3fgOGXM-lHXFkrDYUe/view?usp=sharing

when moving the second Fanta bottle, the tracker updates the track of the first Fanta bottle (track id 6)

tracks: pink box
detections: blue box

Any help on this would be highly appreciated.

**Comment by dyhBUPT** [comment]
Hi, it seems the `det_box` of the second bottle is wrongly matched with the first bottle. It is a failure of the duty of Kalman Filter.

In your case, Kalman Filter is not recommended, maybe the simple IoU works better.
And, modifying the matching procedure for missing tracks (in your case, i.e., the first bottle) would help.

Best wishes.
