### ISSUE TITLE
运行出现错误

### ISSUE THREAD

**Issue by cxzxr123** [dyhBUPT/StrongSORT#95]
运行代码：python strong_sort.py MOT17 val
出现错误如下图，
<img width="645" alt="image" src="https://github.com/dyhBUPT/StrongSORT/assets/64005753/424110db-1da3-4c57-9933-f7e8a99b506e">
搜索资料说是新的scikit-learn版本问题，但我的scikit-learn版本为：0.19.2
将from sklearn.utils.linear_assignment_ import linear_assignment  改为 
from scipy.optimize import linear_sum_assignment as linear_assignment，运行python strong_sort.py MOT17 val，
出现错误如下图，
<img width="736" alt="image" src="https://github.com/dyhBUPT/StrongSORT/assets/64005753/7eaa5cb3-a3d1-4974-a7c6-85c8e3ee1f57">
请问这种问题应怎么解决呢？

**Comment by dyhBUPT** [comment]
Please check the version of your `scikit-learn` package

Or, if you want to use `scipy` instead, please refer to the offcial guidance to rewrite the codes.

**Comment by yuuuuuqing** [comment]
@pandascd 请问你这个问题解决了吗

**Comment by YHQCP3** [comment]
@yuuuuuqing 可以使用scipy代替，CSDN上有方法的
