### ISSUE TITLE
MOT17 results

### ISSUE THREAD

**Issue by Tobelakers** [dyhBUPT/StrongSORT#98]
Hello, thank you for your excellent work.
When I evaluated the results of MOT17, the gt file was officially provided by motchallenge, and the evaluated results are shown in the following figure.
My question is, do different tracker methods have different gt files?
I hope you can answer this question. Thank you very much.
![1702009981217](https://github.com/dyhBUPT/StrongSORT/assets/140885661/4d36d6a4-df56-4986-8dfa-9abe19d004bf)

**Comment by Tobelakers** [comment]
Thank you for your answer and for your excellent work.
Can you answer why different gt files are used and the evaluation results are different?
I hope you can answer, thank you.

**Comment by dyhBUPT** [comment]
The official gt files contains the annotations for all frames.
But in the MOT community, we usually use the first half frames for training, and the second half frames for validation.
Therefore, our tracking results and our provided gt files only contain the second half frames.

Please refer to related papers for more details.
