### ISSUE TITLE
Error when specifying numeric parameters EMA_alpha and MC_lambda

### ISSUE THREAD

**Issue by manuelmollonuam** [dyhBUPT/StrongSORT#99]
While running the tracking process, I attempted to adjust parameters lambda and alpha. However, an error occurred due to the inputs being passed as strings in the configuration, whereas the functions required float values. To resolve this, I performed a casting operation to convert them into float types within opts.py. I'm unsure if I overlooked something or if this is a bug that needs fixing.
Thank you for your work!
Regards.

**Comment by dyhBUPT** [comment]
Hi, thanks for your interest in our work.

It seems like a strange error. Did you modify the code?
Or, how do you adjust these parameters?
A recommended way is like:
```shell
python strong_sort.py MOT17 val --EMA_alpha 0.8
```
